# Generated by Django 5.2.4 on 2025-08-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agentprofile", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcontact",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="service_areas",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="locations.area"
            ),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "agent"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentcontact",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentcertification",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentachievement",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentreview",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="agentreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentschedule",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentreview",
            unique_together={("agent", "reviewer")},
        ),
        migrations.AlterUniqueTogether(
            name="agentschedule",
            unique_together={("agent", "day_of_week")},
        ),
    ]
