# Generated by Django 5.2.4 on 2025-08-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('limit', 'Numeric Limit'), ('boolean', 'Yes/No Feature'), ('text', 'Text Feature')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_core_feature', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('change', 'Plan Change')], max_length=10)),
                ('proration_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('effective_date', models.DateTimeField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('property_created', 'Property Created'), ('photo_uploaded', 'Photo Uploaded'), ('video_uploaded', 'Video Uploaded'), ('api_call', 'API Call'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_audience', models.CharField(choices=[('agents', 'Real Estate Agents'), ('owners', 'Property Owners'), ('developers', 'Property Developers'), ('agencies', 'Real Estate Agencies'), ('individuals', 'Individual Users')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tariff Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('lifetime', 'Lifetime')], max_length=15)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('max_properties', models.PositiveIntegerField(default=1)),
                ('max_photos_per_property', models.PositiveIntegerField(default=5)),
                ('max_videos_per_property', models.PositiveIntegerField(default=0)),
                ('max_virtual_tours', models.PositiveIntegerField(default=0)),
                ('max_featured_properties', models.PositiveIntegerField(default=0)),
                ('max_ad_campaigns', models.PositiveIntegerField(default=0)),
                ('max_promoted_properties', models.PositiveIntegerField(default=0)),
                ('social_media_posting', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('basic_analytics', models.BooleanField(default=True)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('custom_reports', models.BooleanField(default=False)),
                ('export_data', models.BooleanField(default=False)),
                ('email_support', models.BooleanField(default=True)),
                ('phone_support', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('dedicated_manager', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('api_calls_per_month', models.PositiveIntegerField(default=0)),
                ('webhook_support', models.BooleanField(default=False)),
                ('third_party_integrations', models.BooleanField(default=False)),
                ('remove_branding', models.BooleanField(default=False)),
                ('custom_domain', models.BooleanField(default=False)),
                ('custom_themes', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge_text', models.CharField(blank=True, max_length=20)),
                ('highlight_color', models.CharField(default='#007BFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('pending', 'Pending Payment')], default='pending', max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('billing_cycle', models.CharField(max_length=15)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('properties_used', models.PositiveIntegerField(default=0)),
                ('photos_used', models.PositiveIntegerField(default=0)),
                ('videos_used', models.PositiveIntegerField(default=0)),
                ('api_calls_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('is_included', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffplans.planfeature')),
            ],
        ),
    ]
