# Generated by Django 5.2.4 on 2025-08-05 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planupgrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='tariffplans.tariffcategory'),
        ),
        migrations.AddField(
            model_name='planupgrade',
            name='from_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrades_from', to='tariffplans.tariffplan'),
        ),
        migrations.AddField(
            model_name='planupgrade',
            name='to_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrades_to', to='tariffplans.tariffplan'),
        ),
        migrations.AddField(
            model_name='planfeaturevalue',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='tariffplans.tariffplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariffplans.tariffplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tariffplans.usersubscription'),
        ),
        migrations.AlterUniqueTogether(
            name='planfeaturevalue',
            unique_together={('plan', 'feature')},
        ),
    ]
