# Generated by Django 5.2.4 on 2025-08-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentprofile", "0002_initial"),
        ("properties", "0003_alter_property_agent_commission_months_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.AlterField(
            model_name="property",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="agentprofile.agentprofile",
            ),
        ),
    ]
