# Generated by Django 5.2.4 on 2025-08-05 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner_ads/')),
                ('link_url', models.URLField()),
                ('alt_text', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('728x90', 'Leaderboard (728x90)'), ('300x250', 'Medium Rectangle (300x250)'), ('320x50', 'Mobile Banner (320x50)'), ('160x600', 'Wide Skyscraper (160x600)'), ('300x600', 'Half Page (300x600)'), ('970x250', 'Large Leaderboard (970x250)')], max_length=10)),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('search_results', 'Search Results'), ('property_detail', 'Property Detail'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('newsletter', 'Newsletter'), ('social_media', 'Social Media')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=0.001, max_digits=6)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('destination_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('featured_listing', models.BooleanField(default=False)),
                ('priority_placement', models.BooleanField(default=False)),
                ('social_media_boost', models.BooleanField(default=False)),
                ('email_marketing', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
                ('max_photos', models.PositiveIntegerField(default=10)),
                ('max_videos', models.PositiveIntegerField(default=1)),
                ('virtual_tour_included', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('call_to_action', models.CharField(default='View Details', max_length=50)),
                ('target_url', models.URLField(blank=True)),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('search_results', 'Search Results'), ('property_detail', 'Property Detail'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('newsletter', 'Newsletter'), ('social_media', 'Social Media')], default='search_results', max_length=20)),
                ('target_audience', models.TextField(blank=True, help_text='Target audience description')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('featured', 'Featured Property'), ('hot_deal', 'Hot Deal'), ('price_reduced', 'Price Reduced'), ('new_listing', 'New Listing'), ('urgent_sale', 'Urgent Sale'), ('premium', 'Premium Listing')], max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('priority_score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('highlight_color', models.CharField(default='#FF6B35', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
