# Generated by Django 5.2.4 on 2025-08-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ad", "0001_initial"),
        ("agentprofile", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adbanner",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banner_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adclick",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ad.adpackage"
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="property_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisements",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="advertisement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impression_logs",
                to="ad.advertisement",
            ),
        ),
        migrations.AddField(
            model_name="adclick",
            name="advertisement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="click_logs",
                to="ad.advertisement",
            ),
        ),
        migrations.AddField(
            model_name="promotedproperty",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoted_properties",
                to="agentprofile.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="promotedproperty",
            name="property_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="properties.property",
            ),
        ),
    ]
