# Generated by Django 5.2.4 on 2025-08-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediagallery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediagallery",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.mediagallery"
            ),
        ),
        migrations.AddField(
            model_name="imagetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="media.mediatag",
            ),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediagallery",
            name="images",
            field=models.ManyToManyField(
                blank=True, through="media.GalleryImage", to="media.propertyimage"
            ),
        ),
        migrations.AddField(
            model_name="imagetag",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="media.propertyimage",
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.propertyimage"
            ),
        ),
        migrations.AddField(
            model_name="propertyvideo",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="propertyvideo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediagallery",
            name="videos",
            field=models.ManyToManyField(blank=True, to="media.propertyvideo"),
        ),
        migrations.AddField(
            model_name="virtualtour",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="virtualtour",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtual_tours",
                to="properties.property",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="imagetag",
            unique_together={("image", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="galleryimage",
            unique_together={("gallery", "image")},
        ),
    ]
